name: Publications Cronjob

on:
  schedule:
    - cron: '17 5 * * 1' # At 5.17am every Monday
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cronjobpublications:
    name: Publications Cronjob
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Publications Cronjob
        id: run-publications-cronjob
        uses: ./
        with:
          download-limit: '15'
          num-publications: '50'
          commit: 'true'
          'commit-repo': 'NationalGenomicsInfrastructure/ngisweden.se-publications'
          'commit-token': ${{ secrets.TOKEN_FOR_PUBLICATION_COMMITS }}
          'commit-message': 'Update NGI Publications'
          'html-path': 'cache/publications.html'
          'json-path': 'cache/publications.json'
